<a href="https://colab.research.google.com/github/arguntolga/ts_jupyter/blob/main/marmon3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import yfinance as yf
import pandas as pd

# Define your two stock tickers
stock_list = ["MSFT", "NVDA", "CVX", "TSLA"]

# Set start and end dates
start_date = "2023-01-04"
end_date = "2024-05-24"

# Download data using yfinance
data = yf.download(stock_list, start=start_date, end=end_date)["Adj Close"]

print(data)

def calculate_moving_averages(stock_list, data, window_sizes):
  for stock in stock_list:
    for window in window_sizes:
      data[stock + '_MA_' + str(window)] = data[stock].rolling(window=window).mean()
  return data

def calculate_above_below_ma(stock_list, data, window_sizes):
  above_below_counts = {}
  for date in data.index:
    daily_counts = {"Date": date}
    for window in window_sizes:
      above_count = 0
      for stock in stock_list:
        ma_col = f"{stock}_MA_{window}"
        above_count += (data.loc[date, stock] > data.loc[date, ma_col])
      below_count = len(stock_list) - above_count
      daily_counts["Above MA" + str(window)] = above_count
      daily_counts["Below MA" + str(window)] = below_count
    above_below_counts[date] = daily_counts
  return pd.DataFrame(above_below_counts).transpose()

# Define window sizes for moving averages
window_sizes = [10, 20, 50, 100, 200]

# Apply the moving average calculation
data_with_ma = calculate_moving_averages(stock_list, data.copy(), window_sizes)
print(data_with_ma)

# Calculate above/below MA counts
above_below_data = calculate_above_below_ma(stock_list, data_with_ma.copy(), window_sizes)

print(above_below_data)

display(above_below_data)

[*********************100%%**********************]  4 of 4 completed

Ticker             CVX        MSFT         NVDA        TSLA
Date
2023-01-04  162.206390  226.259171   147.417679  113.639999
2023-01-05  165.127518  219.553360   142.580048  110.339996
2023-01-06  166.371323  222.140869   148.517120  113.059998
2023-01-09  165.070953  224.303726   156.203354  119.769997
2023-01-10  165.881317  226.012283   159.011963  118.849998
...                ...         ...          ...         ...
2024-05-17  162.669998  420.209991   924.789978  177.460007
2024-05-20  161.139999  425.339996   947.799988  174.949997
2024-05-21  159.970001  429.040009   953.859985  186.600006
2024-05-22  157.570007  430.519989   949.500000  180.110001
2024-05-23  156.940002  427.000000  1037.989990  173.740005

[349 rows x 4 columns]
Ticker             CVX        MSFT         NVDA        TSLA  MSFT_MA_10  \
Date
2023-01-04  162.206390  226.259171   147.417679  113.639999         NaN
2023-01-05  165.127518  219.553360   142.580048  110.339996         NaN
2023-01-06  166.371323  222.140869   148.517120  113.059998         NaN
2023-01-09  165.070953  224.303726   156.203354  119.769997         NaN
2023-01-10  165.881317  226.012283   159.011963  118.849998         NaN
...                ...         ...          ...         ...         ...
2024-05-17  162.669998  420.209991   924.789978  177.460007  414.983524
2024-05-20  161.139999  425.339996   947.799988  174.949997  416.237979
2024-05-21  159.970001  429.040009   953.859985  186.600006  418.281680
2024-05-22  157.570007  430.519989   949.500000  180.110001  420.353595
2024-05-23  156.940002  427.000000  1037.989990  173.740005  421.895831

Ticker      MSFT_MA_20  MSFT_MA_50  MSFT_MA_100  MSFT_MA_200  NVDA_MA_10  ...  \
Date                                                                      ...
2023-01-04         NaN         NaN          NaN          NaN         NaN  ...
2023-01-05         NaN         NaN          NaN          NaN         NaN  ...
2023-01-06         NaN         NaN          NaN          NaN         NaN  ...
2023-01-09         NaN         NaN          NaN          NaN         NaN  ...
2023-01-10         NaN         NaN          NaN          NaN         NaN  ...
...                ...         ...          ...          ...         ...  ...
2024-05-17  407.828906  414.054166   405.449104   373.045244  914.953998  ...
2024-05-20  409.084003  414.451193   405.969553   373.551322  917.593994  ...
2024-05-21  410.194194  414.956160   406.532880   374.070343  922.425995  ...
2024-05-22  411.304019  415.275914   407.098952   374.585205  926.963995  ...
2024-05-23  412.737943  415.528862   407.622251   375.102609  942.015997  ...

Ticker       CVX_MA_10   CVX_MA_20   CVX_MA_50  CVX_MA_100  CVX_MA_200  \
Date
2023-01-04         NaN         NaN         NaN         NaN         NaN
2023-01-05         NaN         NaN         NaN         NaN         NaN
2023-01-06         NaN         NaN         NaN         NaN         NaN
2023-01-09         NaN         NaN         NaN         NaN         NaN
2023-01-10         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2024-05-17  162.063429  161.604102  158.039718  152.589501  152.148833
2024-05-20  162.109679  161.646038  158.294884  152.708324  152.188171
2024-05-21  162.002299  161.583438  158.484675  152.820344  152.223387
2024-05-22  161.667792  161.365199  158.628644  152.929321  152.243819
2024-05-23  160.982191  161.030814  158.720413  153.037971  152.262253

Ticker      TSLA_MA_10  TSLA_MA_20  TSLA_MA_50  TSLA_MA_100  TSLA_MA_200
Date
2023-01-04         NaN         NaN         NaN          NaN          NaN
2023-01-05         NaN         NaN         NaN          NaN          NaN
2023-01-06         NaN         NaN         NaN          NaN          NaN
2023-01-09         NaN         NaN         NaN          NaN          NaN
2023-01-10         NaN         NaN         NaN          NaN          NaN
...                ...         ...         ...          ...          ...
2024-05-17  175.346001  172.965500  170.807800     188.8141    215.15960
2024-05-20  174.365001  174.610500  170.800000     187.9975    214.73775
2024-05-21  175.244002  176.706500  170.976600     187.2491    214.40145
2024-05-22  175.783002  177.605500  171.028000     186.5184    214.04475
2024-05-23  175.960002  177.783501  171.113201     185.7710    213.66495

[349 rows x 24 columns]
                 Date Above MA10 Below MA10 Above MA20 Below MA20 Above MA50  \
2023-01-04 2023-01-04          0          4          0          4          0
2023-01-05 2023-01-05          0          4          0          4          0
2023-01-06 2023-01-06          0          4          0          4          0
2023-01-09 2023-01-09          0          4          0          4          0
2023-01-10 2023-01-10          0          4          0          4          0
...               ...        ...        ...        ...        ...        ...
2024-05-17 2024-05-17          4          0          4          0          4
2024-05-20 2024-05-20          3          1          3          1          4
2024-05-21 2024-05-21          3          1          3          1          4
2024-05-22 2024-05-22          3          1          3          1          3
2024-05-23 2024-05-23          2          2          2          2          3

           Below MA50 Above MA100 Below MA100 Above MA200 Below MA200
2023-01-04          4           0           4           0           4
2023-01-05          4           0           4           0           4
2023-01-06          4           0           4           0           4
2023-01-09          4           0           4           0           4
2023-01-10          4           0           4           0           4
...               ...         ...         ...         ...         ...
2024-05-17          0           3           1           3           1
2024-05-20          0           3           1           3           1
2024-05-21          0           3           1           3           1
2024-05-22          1           3           1           3           1
2024-05-23          1           3           1           3           1

[349 rows x 11 columns]

,Date,Above MA10,Below MA10,Above MA20,Below MA20,Above MA50,Below MA50,Above MA100,Below MA100,Above MA200,Below MA200
2023-01-04,2023-01-04,0,4,0,4,0,4,0,4,0,4
2023-01-05,2023-01-05,0,4,0,4,0,4,0,4,0,4
2023-01-06,2023-01-06,0,4,0,4,0,4,0,4,0,4
2023-01-09,2023-01-09,0,4,0,4,0,4,0,4,0,4
2023-01-10,2023-01-10,0,4,0,4,0,4,0,4,0,4
...,...,...,...,...,...,...,...,...,...,...,...
2024-05-17,2024-05-17,4,0,4,0,4,0,3,1,3,1
2024-05-20,2024-05-20,3,1,3,1,4,0,3,1,3,1
2024-05-21,2024-05-21,3,1,3,1,4,0,3,1,3,1
2024-05-22,2024-05-22,3,1,3,1,3,1,3,1,3,1
2024-05-23,2024-05-23,2,2,2,2,3,1,3,1,3,1